### ISSUE TITLE
Crashing during compiling

### ISSUE THREAD

**Issue by hutouski-aliaksei** [EchterAlsFake/PySide6-to-Android#4]
Hi, may be you have an idea about this error?

```
Compiling '/home/user/DoseCalculatorModern/.buildozer/android/app/venv-2/lib64/python3.11/site-packages/PySide6/scripts/deploy_lib/android/recipes/PySide6/__init__.tmpl.py'...
***   File "/home/user/DoseCalculatorModern/.buildozer/android/app/venv-2/lib64/python3.11/site-packages/PySide6/scripts/deploy_lib/android/recipes/PySide6/__init__.tmpl.py", line 39
    {% for module in qt_modules %}  # noqa: E999
     ^
SyntaxError: invalid syntax
```
I am using PySide 6.8.1 and your wheels, but the same take place with PySide 6.8.0 and wheels from Qt.
All actions I performed according to your manual.
Python version is 3.11.

Thank you for attention))

**Comment by EchterAlsFake** [comment]
Hi, this is because you have a virtual environment inside of your compilation directory. Buildozer will compile all .py files in this directory and it will then start compiling PySide6 which will throw an error. You need to put your virtual environment outside of your build directory and then it should work.

**Comment by hutouski-aliaksei** [comment]
Oh, great thank you! It is finally compiled.
